
exports.T={
    days:10,
    strategyName:'本地数据查找最近收T的股票！！',
    baseDay:{
        formulas:[
            '(H-L)/L>0.06',
            '(O-L)/(H-L)>0.65',
            '(C-L)/(H-L)>0.65'
        ]
    }
};

exports.SingleSunKeepDays={
    days:20,
    strategyName:'本地数据查找最近单阳不破的股票！！',
    baseDay:{
        formulas:[
            '(C-O)/O>0.055',
            '(C-O)/O<0.095',
        ]
    },
    laterDays:{
        formulas:[
            'every("(c-o)/o<=0.018",4)',
            'every("(c-o)/o>=-0.018",4)',
            'every("(o-O)/(C-O)>0.66",4)',
            'every("(c-O)/(C-O)>0.66",4)',
        ]
    }
};

exports.bouncePrice={
    days:10,
    strategyName:'本地数据查找最近涨幅居前的股票！！',
    baseDay:{
        formulas:[
            '(C-O)/O>0.07'
        ]
    }
};

exports.bounceVol={
    days:80,
    strategyName:'本地数据查找最近成交量暴涨的股票！！',
    baseDay:{
        formulas:[
            '(C-O)/O>0.05'
        ]
    },
    passDays:{
        formulas:[
            'max("vol",15)-VOL*0.2<0',//前5日最大成交量不高于vol*0.6
        ]
    },
};

exports.singleSunUpClosedAverage={
    days:40,
    strategyName:'本地数据查找最近单阳突破密集均线的股票！！',
    baseDay:{
        formulas:[
            '(C-O)/O>=0.045',
            // '(C-O)/O<=0.1',
            'H<=C*1.007',//不能有长上影线
            'C>_60',
            'O*1+(C-O)*0.3>Math.max(_5,_10,_20,_40)',
            'Math.max(_5,_10,_20,_40)<Math.min(_5,_10,_20,_40)*1.035',
            '_5>_10'
        ]
    },
    passDays:{
        formulas:[
            'every("(c-o)/o<0.03",5)',
            'every("(c-o)/o>-0.02",5)',
            // 'every("Math.max(_5,_10,_20,_40)<Math.min(_5,_10,_20,_40)*1.035",6)'
            // 'every("_5>_10",2)',//会限制掉很多很好的票
        ]
    }
}

exports.downAndUpRegular={
    days:120,
    strategyName:'本地数据查找反复震荡的股票！！',
    baseDay:{
        formulas:[
            '(C-O)/O<-0.04'
        ]
    },
    passDays:{
        formulas:[
            'every("(c-o)/o<0.005",3)',
            'every("(c-o)/o>-0.02",3)',
            'count("(c-o)/o>0.04",6)==1'
        ]
    },
    laterDays:{
        formulas:[
            'every("(c-o)/o>0.005",3)',
            'count("(c-o)/o>0.04",6)==1'
        ]
    }
}
